name: On push Update Changes.md

on:
  push:
  workflow_call:

permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v4
      - name: "✏️ Generate changelog"
        uses: heinrichreimer/action-github-changelog-generator@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          headerLabel: # Changelog for ${{github.event.repository.name}}
      - name: Checkin CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update CHANGELOG.md

      
          
